const APIConstants = {
  MISSING_PARAMETERS : 'MISSING_PARAMETERS',
  INTERNAL_SERVER_ERROR : 'INTERNAL_SERVER_ERROR',
  CONFLICT : 'CONFLICT',
  DATABASE_ERROR : 'DATABASE_ERROR',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS'
}

export default APIConstants;
