const APIConstants = {
  MISSING_PARAMETERS : 'MISSING_PARAMETERS',
  BAD_REQUEST : 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR : 'INTERNAL_SERVER_ERROR',
  CONFLICT : 'CONFLICT',
  UNAUTHORIZED : 'UNAUTHORIZED',
  DATABASE_ERROR : 'DATABASE_ERROR',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS : 'LOGOUT_SUCCESS'
}

export default APIConstants;
